### ISSUE TITLE
Unable to reproduce experiment result

### ISSUE THREAD

**Issue by tongyao-zhu** [neccam/slt#1]
Hi. I'm highly interested in your paper about sign language transformers on arXiv and have tried to implement the paper. I modified joeynmt and used the hyperparameters suggested in the paper. However, the performance seems much worse. Could you please provide more details about your implementation? Thanks!

**Comment by neccam** [comment]
Thanks for the interest. 

We will be releasing the code with the publication of the paper, which will enable you to reproduce the results in the paper.

I am closing the issue for now, feel free to open another one once the code is released.
